import { ArticleTypes } from 'lib/types'

export const BlogData: ArticleTypes[] = [
    {
        title: 'Est amet dolore nisi ut esse adipisicing aute qui deserunt enim sint voluptate ullamco aliquip.',
        author: 'Morgan Goldbreg',
        avatar: '/avatar_small.png',
        category: 'Design Inspiration',
        date: new Date(2022, 10, 1).toJSON(),
        thumbnail: '/thumbnail.jpg',
        summary:
            'Ad Lorem qui esse labore irure consequat est sunt duis ipsum qui excepteur.',
        content: '',
    },
    {
        title: 'Exercitation occaecat nulla do ipsum consectetur quis amet occaecat.',
        author: 'Rizal Ahmad',
        avatar: '/avatar_small.png',
        category: 'Color Guide',
        date: new Date(2022, 10, 2).toJSON(),
        thumbnail: '/thumbnail.jpg',
        summary: 'Laboris consequat mollit consectetur ullamco dolore.',
        content: '',
    },
    {
        title: 'Aliquip anim dolor eiusmod nulla incididunt dolor dolore cillum reprehenderit culpa id.',
        author: 'Filipus Fendi',
        avatar: '/avatar_small.png',
        category: 'Tips and Trick',
        date: new Date(2022, 10, 23).toJSON(),
        thumbnail: '/thumbnail.jpg',
        summary: 'Eiusmod cupidatat dolore in occaecat culpa. ',
        content: '',
    },
    {
        title: 'Cupidatat aliquip eiusmod laboris nulla sint ullamco in ea culpa officia dolor reprehenderit.',
        author: 'Jane Doe',
        avatar: '/avatar_small.png',
        category: 'Color Guide',
        date: new Date(2022, 11, 5).toJSON(),
        thumbnail: '/thumbnail.jpg',
        summary: 'Eiusmod cupidatat dolore in occaecat culpa. ',
        content: '',
    },
    {
        title: 'Mollit mollit sint adipisicing magna reprehenderit culpa proident anim.',
        author: 'John Doe',
        avatar: '/avatar_small.png',
        category: 'Tips and Trick',
        date: new Date(2022, 10, 3).toJSON(),
        thumbnail: '/thumbnail.jpg',
        summary: 'Eiusmod cupidatat dolore in occaecat culpa. ',
        content: '',
    },
]
