import { ArticleTypes } from "lib/types";

export const BlogData: ArticleTypes[] = [
  {
    title: "string",
    author: "Morgan Goldbreg",
    avatar: "/avatar_small.png",
    category: "Design Inspiration",
    date: new Date(2022, 10, 1).toJSON(),
    thumbnail: "/thumbnail.jpg",
    summary:
      "Ad Lorem qui esse labore irure consequat est sunt duis ipsum qui excepteur.",
    content: "",
  },
  {
    title: "string",
    author: "Rizal Ahmad",
    avatar: "/avatar_small.png",
    category: "Color Guide",
    date: new Date(2022, 10, 2).toJSON(),
    thumbnail: "/thumbnail.jpg",
    summary: "Laboris consequat mollit consectetur ullamco dolore.",
    content: "",
  },
  {
    title: "string",
    author: "Filipus Fendi",
    avatar: "/avatar_small.png",
    category: "Tips and Trick",
    date: new Date(2022, 10, 23).toJSON(),
    thumbnail: "/thumbnail.jpg",
    summary: "Eiusmod cupidatat dolore in occaecat culpa. ",
    content: "",
  },
  {
    title: "string",
    author: "Jane Doe",
    avatar: "/avatar_small.png",
    category: "Color Guide",
    date: new Date(2022, 11, 5).toJSON(),
    thumbnail: "/thumbnail.jpg",
    summary: "Eiusmod cupidatat dolore in occaecat culpa. ",
    content: "",
  },
  {
    title: "string",
    author: "John Doe",
    avatar: "/avatar_small.png",
    category: "Tips and Trick",
    date: new Date(2022, 10, 3).toJSON(),
    thumbnail: "/thumbnail.jpg",
    summary: "Eiusmod cupidatat dolore in occaecat culpa. ",
    content: "",
  },
];
