import { ArticleTypes } from "lib/types";

export const BlogData: ArticleTypes[] = [
  {
    title: "string",
    author: "Morgan Goldbreg",
    avatar: "",
    category: "Design Inspiration",
    date: new Date(),
    thumbnail: "",
    summary:
      "Ad Lorem qui esse labore irure consequat est sunt duis ipsum qui excepteur.",
    content: "",
  },
  {
    title: "string",
    author: "Rizal Ahmad",
    avatar: "",
    category: "Color Guide",
    date: new Date(),
    thumbnail: "",
    summary: "Laboris consequat mollit consectetur ullamco dolore.",
    content: "",
  },
  {
    title: "string",
    author: "Filipus Fendi",
    avatar: "",
    category: "Tips and Trick",
    date: new Date(),
    thumbnail: "",
    summary: "Eiusmod cupidatat dolore in occaecat culpa. ",
    content: "",
  },
  {
    title: "string",
    author: "Jane Doe",
    avatar: "",
    category: "Color Guide",
    date: new Date(),
    thumbnail: "",
    summary: "Eiusmod cupidatat dolore in occaecat culpa. ",
    content: "",
  },
  {
    title: "string",
    author: "John Doe",
    avatar: "",
    category: "Tips and Trick",
    date: new Date(),
    thumbnail: "",
    summary: "Eiusmod cupidatat dolore in occaecat culpa. ",
    content: "",
  },
];
